[package]
name = "minecraftclone"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"

[dependencies]
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
anyhow = "1.0.97"
bevy_framepace = { version = "0.18.1", default-features = false }
rand = "0.9.0"
wgpu-types = "23.0.0"
toml = "0.8.20"
serde = { version = "1.0.219", features = ["derive"] }

[dependencies.bevy]
version = "0.15.3"
default-features = false
features = [
#	 "android-game-activity", and next - needed for android support
#	 "android_shared_stdcxx",
	 "animation",
	 "bevy_animation",
	 "bevy_asset",
	 "bevy_audio",
	 "bevy_color",
	 "bevy_core_pipeline",
	 "bevy_gilrs",
	 "bevy_gizmos",
	 "bevy_gltf",
	 "bevy_mesh_picking_backend",
#	 "bevy_pbr" probe reflections
	 "bevy_picking",
	 "bevy_render",
	 "bevy_scene", # useless not to use, it s optional everywhere
	 "bevy_sprite",
	 "bevy_sprite_picking_backend",
	 "bevy_state",
	 "bevy_text",
	 "bevy_ui",
	 "bevy_ui_picking_backend",
	 "bevy_window",
	 "bevy_winit",
#	 "custom_cursor",
	 "default_font", # default fallback font
	 "dynamic_linking",
	 "hdr",
	 "ktx2",
	 "multi_threaded",
	 "png", # png image support
	 "smaa_luts",
	 "sysinfo_plugin",
	 "tonemapping_luts", # needed for camera2d/camera3d
	 "vorbis",
#	 "webgl2", for web
	 "x11",
	 "zstd" # optional for ktx2
	 ]
