[package]
name = "librecraft_server"
version = "0.2.1"
edition = "2024"

[dependencies]
librecraft_shared = { path = "../shared" }
clap = { version = "4.5.37", default-features = false, features = ["std"] }
[lints]
workspace = true
